plugin:
    name: 'mixtapes.mixtapes::lang.plugin.name'
    description: 'mixtapes.mixtapes::lang.plugin.description'
    author: 'Budi Iyok Prakosa'
    icon: oc-icon-bug
    homepage: ''
navigation:
    main-menu-item:
        label: Mixtapes
        url: mixtapes/mixtapes/mixtapes
        icon: icon-birthday-cake
