plugin:
    name: 'mixtapes.mixtapes::lang.plugin.name'
    description: 'mixtapes.mixtapes::lang.plugin.description'
    author: 'Budi Iyok Prakosa'
    icon: oc-icon-bug
    homepage: ''
navigation:
    main-menu-item:
        label: Mixtapes
        url: mixtapes/mixtapes/mixtapes
        icon: icon-birthday-cake
        sideMenu:
            side-menu-item3:
                label: Mixtape
                url: mixtapes/mixtapes/mixtapes
                icon: icon-sitemap
            side-menu-item2:
                label: 'Mixtape Tag'
                url: mixtapes/mixtapes/mixtapetag
                icon: icon-sitemap
            side-menu-item:
                label: Settings
                url: mixtapes/mixtapes/settings
                icon: icon-sitemap
