title: Mixtapes
modelClass: Mixtapes\Mixtapes\Models\Mixtape
list: $/mixtapes/mixtapes/models/mixtape/columns.yaml
recordUrl: 'mixtapes/mixtapes/mixtapes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
